services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: open_dateaubase_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPwd123!"
      MSSQL_PID: "Developer"
    ports:
      - "14330:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: open_dateaubase_db_init
    depends_on:
      - db
    volumes:
      - ./sql:/sql
    entrypoint: /bin/bash -c "
      echo 'Waiting for SQL Server...';
      for i in {1..30}; do
        /opt/mssql-tools/bin/sqlcmd -S db,1433 -U SA -P 'StrongPwd123!' -Q 'SELECT 1' && break;
        sleep 2;
      done;
      echo 'Running init.sql...';
      /opt/mssql-tools/bin/sqlcmd -S db,1433 -U SA -P 'StrongPwd123!' -i /sql/init.sql;
      echo 'Done.'; "
    restart: "no"

  api:
    build: .
    container_name: open_dateaubase_api
    env_file:
      - .env.docker
    depends_on:
      - db
      - db-init
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  streamlit:
    build: .
    container_name: open_dateaubase_streamlit
    env_file:
      - .env.docker
    depends_on:
      - api
      - db
    command: python -m streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  mssql_data:
